//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaManagementDBEntities : DbContext
    {
        public CinemaManagementDBEntities()
            : base("name=CinemaManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbNguoiDung> tbNguoiDungs { get; set; }
        public virtual DbSet<tbPhim> tbPhims { get; set; }
        public virtual DbSet<tbPhongChieu> tbPhongChieux { get; set; }
        public virtual DbSet<tbLichChieu> tbLichChieux { get; set; }
        public virtual DbSet<tbVeXemPhim> tbVeXemPhims { get; set; }
    }
}
