//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLichChieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbLichChieu()
        {
            this.tbVeXemPhims = new HashSet<tbVeXemPhim>();
        }
    
        public int MaLich { get; set; }
        public Nullable<int> MaPhim { get; set; }
        public Nullable<int> MaPhong { get; set; }
        public Nullable<System.DateTime> NgayChieu { get; set; }
        public Nullable<System.TimeSpan> GioChieu { get; set; }
        public Nullable<decimal> GiaVe { get; set; }
    
        public virtual tbPhim tbPhim { get; set; }
        public virtual tbPhongChieu tbPhongChieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbVeXemPhim> tbVeXemPhims { get; set; }
    }
}
