//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNguoiDung
    {
        public int MaND { get; set; }
        public string HoTen { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Passwd { get; set; }
        public string Roles { get; set; }
    }
}
