//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPhongChieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPhongChieu()
        {
            this.tbLichChieux = new HashSet<tbLichChieu>();
        }
    
        public int MaPhong { get; set; }
        public string LoaiPhong { get; set; }
        public int SoGhe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLichChieu> tbLichChieux { get; set; }
    }
}
