//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPhim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPhim()
        {
            this.tbLichChieux = new HashSet<tbLichChieu>();
        }
    
        public int MaPhim { get; set; }
        public string TenPhim { get; set; }
        public string TheLoai { get; set; }
        public Nullable<int> ThoiLuong { get; set; }
        public string DaoDien { get; set; }
        public Nullable<System.DateTime> NgayKhoiChieu { get; set; }
        public string Poster { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLichChieu> tbLichChieux { get; set; }
    }
}
