//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbVeXemPhim
    {
        public int MaVe { get; set; }
        public Nullable<int> MaLich { get; set; }
        public string ViTriGhe { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual tbLichChieu tbLichChieu { get; set; }
    }
}
